version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - node --version
      - npm --version

  build:
    commands:
      - sam build -c -p

artifacts:
  files:
    - template.yaml
    - packaged.yaml