version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm update -g npm
      - npm install -g yarn
      - node -v
      - npm -v
      - yarn -v

  build:
    commands:
      # Build/package the backend
      - sam build -c -p
      - echo $S3_BUCKET
      - sam package --template-file .aws-sam/build/template.yaml --s3-bucket $S3_BUCKET --output-template-file packaged-template.yaml
      # Copy custom embeds from source to the build folder
      - |
        if [ -d "$CODEBUILD_SRC_DIR_Embeds" ]; then
          # Copy custom embeds from source to the build folder
          cp -R "$CODEBUILD_SRC_DIR_Embeds"/* client/src/components/posts/embeds/domains_custom/
          ls -la client/src/components/posts/embeds/domains_custom/
        else
          echo "Source directory not found. Skipping copy."
        fi
      # Build the frontend
      - cd client
      - yarn install
      # get the .env file from SSM
      - aws ssm get-parameter --name $ENV_SSM_PARAM --query Parameter.Value --output text > .env.production
      - cat .env.production
      - cp .env.production .env # needed for the build
      - yarn build
      # Debug: List files in the build directory
      - ls -la dist
      # Navigate back to the parent directory
      - cd ..

artifacts:
  files:
    - packaged-template.yaml
    - client/dist/**/*
