version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm update -g npm
      - npm install -g yarn
      - node -v
      - npm -v
      - yarn -v

  build:
    commands:
      # Build the backend
      - sam build -c -p
      # Copy custom embeds from source to the build folder
      - |
        if [ -d "$CODEBUILD_SRC_DIR_Embeds" ]; then
          # Copy custom embeds from source to the build folder
          cp -R "$CODEBUILD_SRC_DIR_Embeds"/* client/src/components/posts/embeds/domains_custom/
          ls -la client/src/components/posts/embeds/domains_custom/
        else
          echo "Source directory not found. Skipping copy."
        fi
      # Build the frontend
      - cd client
      - yarn install
      # get the .env file from SSM
      - aws ssm get-parameter --name $ENV_SSM_PARAM --query Parameter.Value --output text > .env.production
      - cat .env.production
      - cp .env.production .env # needed for the build
      - yarn build

  post_build:
    commands:
      # Deploy the frontend to S3
      - aws s3 cp client/dist $FRONTEND_S3 --recursive
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
      - echo "Clearing Cloudflare Cache"
      - |
        curl -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" \
        -H "X-Auth-Email: $CLOUDFLARE_EMAIL" \
        -H "X-Auth-Key: $CLOUDFLARE_API_KEY" \
        -H "Content-Type: application/json" \
        --data '{"purge_everything":true}'

artifacts:
  files:
    - template.yaml
    - client/dist/**/*