version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm update -g npm
      - npm install -g yarn
      - node -v
      - npm -v
      - yarn -v

  build:
    commands:
      # Build the backend
      - sam build -c -p
      # Copy artifacts from source to build folder
      - ls -la $CODEBUILD_SRC_DIR
      - pwd
      # Build the frontend
      - cd client
      - yarn install
      # get the .env file from SSM
      - aws ssm get-parameter --name $ENV_SSM_PARAM --query Parameter.Value --output text > .env.production
      - yarn build

artifacts:
  files:
    - template.yaml
    - client/dist/**/*