version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - node --version
      - npm --version
      - yarn --version

  build:
    commands:
      # Build the backend
      - sam build -c -p --use-container
      # Build the frontend
      - cd client
      - yarn install
      # get the .env file from SSM
      - aws ssm get-parameter --name $ENV_SSM_PARAM --query Parameter.Value --output text > .env.production
      - yarn build

artifacts:
  files:
    - template.yaml
    - client/dist